name: 'release'
on:
  release:
    types: [published]

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update gist
        uses: ./update-gist
